# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b5b64af7f82a77a881dc260abc7ff7407c96917e5bb75c3044677f7b2cc5cbb6458f505b41350dafeb26880c6ef2219437a68b21db13769071030a94284786d

test:
  secret_key_base: f18510d21c8ceab41168f041f2b559facd2af98068fa5fbfc578e647cc61fa4132f53933ec53d46e6b918d37c39c2996b993ffcc9d723e4162104c5a21ffc520

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
